### ISSUE TITLE
Use bed lots

### ISSUE THREAD

**Issue by thatmacguy** [michaelchadwick/gemwarrior#55]
allow for a way to sleep until at full health?

**Comment by michaelchadwick** [comment]
I believe I will change the bed to just go until healed, much like tents. However, it's too easy to use since there are no random attacks from monsters, so I feel like there needs to be some difficulty in returning to it once you leave home.

Resting without a tent has to have some danger (monsters attacking and lack of full health rest per use), so it will stay the same.

**Comment by michaelchadwick** [comment]
This has been implemented in [0.12.1](https://github.com/michaelchadwick/gemwarrior/releases/tag/v0.12.1).
